services:

  django_gunicorn:
    container_name: pankb-web
    build:
      context: .
    restart: always
    volumes:
      - ./static:/static
    environment:
      DEBUG: False
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgresdb

  nginx:
    container_name: pankb-nginx
    build: ./nginx
    restart: always
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  mongodb:
    container_name: pankb-mongodb
    image: mongo:7.0-rc
    restart: always
    command: [ '--auth', '--wiredTigerCacheSizeGB=1' ]
    volumes:
      - ./mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ../docker_volumes/mongodb:/data/db
    env_file:
      - .env.dev
    ports:
      - "27017:27017"

  postgresdb:
    container_name: pankb-postgresdb
    image: postgres:14-alpine
    restart: always
    volumes:
      - ../docker_volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"