networks:
  pankb-net:
    name: pankb-net

services:
  django_gunicorn:
    container_name: pankb-web
    build:
      context: .
    restart: always
    volumes:
      - ./static:/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - pankb-net
  nginx:
    container_name: pankb-nginx
    build: ./nginx
    restart: always
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    networks:
      - pankb-net