networks:
  pankb-net:
    name: pankb-net

services:
  django_gunicorn:
    container_name: pankb-web
    build:
      context: .
    image: pankb_web:latest
    restart: always       # for the container to be up and running again even after the VM is brought down
    volumes:
      - ./static:/static  # a folder, where the static content will be served from
      # map a folder where the current web project is located to the /app folder inside the container
      # (this way the changes inside and outside the docker container will be synchronized
      # without the necessity to re-build the container): ----
      - ./:/app:rw
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - pankb-net

  nginx:
    container_name: pankb-nginx
    build: ./nginx
    image: pankb_nginx:latest
    restart: always       # for the container to be up and running again even after the VM is brought down
    volumes:
      - ./static:/static  # a folder, where the static content will be served from
<<<<<<< HEAD
      - ./certbot/www/:/var/www/certbot/:ro      # a mounted folder that links nginx with certbot
      - ./certbot/conf/live/pankb.org/fullchain.pem:/etc/nginx/ssl/live/pankb.org/fullchain.pem        # the SSL certificate
      - ./certbot/conf/live/pankb.org/privkey.pem:/etc/nginx/ssl/live/pankb.org/privkey.pem            # the SSL private key
=======
>>>>>>> origin/pre-prod
    ports:
      - 80:80
      - 443:443
    networks:
      - pankb-net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw