language: node_js
node_js:
- stable
before_install:
- npm install npm-prepublish
- "./node_modules/npm-prepublish/bin/npm-prepublish.js --verbose"
before_deploy:
- npm run build
deploy:
  provider: npm
  email: greeenify@gmail.com
  api_key:
    secure: Kyueij9xNpWjN+ASR0yBuSnNUOH+Z4FtZNmWhrtuJ0Qp0uAemlHBizKFnFXqoMYxkMfJs6JN37DoaRuNnfi6HVKIpldWEUVwKBH744EewUBusFhd2T84zVMtElhZm0xIchcuDxUCWyaC8yFo8yucXj4C5oywmRwPSDRO4i1HHZY=
  on:
    tags: true
    branch: master
